import crypto from 'crypto';
/**
 * Creates a placeholder video entry in Bunny.net Stream.
 * @param title The name of the video (e.g., "Calculus Lesson 1").
 * @returns The unique video GUID generated by Bunny.
 */
export const createBunnyVideoEntry = async (title: string): Promise<string> => {
  const libraryId = process.env.BUNNY_LIBRARY_ID;
  const apiKey = process.env.BUNNY_API_KEY;

  if (!libraryId || !apiKey) {
    throw new Error("Critical: Bunny API credentials are missing from .env");
  }

  const url = `https://video.bunnycdn.com/library/${libraryId}/videos`;

  const options = {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
      'AccessKey': apiKey, // This is how Bunny authenticates your backend
    },
    body: JSON.stringify({ title }),
  };

  try {
    const response = await fetch(url, options);

    if (!response.ok) {
      const errorData = await response.text();
      throw new Error(`Bunny API Error (${response.status}): ${errorData}`);
    }

    const data = (await response.json()) as BunnyVideoResponse;
    
    // The 'guid' is the critical Video ID we need for the actual upload
    return data.guid; 

  } catch (error) {
    console.error("[Drive Service] Failed to create Bunny video entry:", error);
    throw error;
  }
};

/**
 * Generates the secure SHA256 signature required for direct TUS uploads.
 * @param videoId The GUID returned from createBunnyVideoEntry.
 */
export const generateTusUploadCredentials = (videoId: string) => {
  const libraryId = process.env.BUNNY_LIBRARY_ID;
  const apiKey = process.env.BUNNY_API_KEY;

  if (!libraryId || !apiKey) {
    throw new Error("Critical: Bunny API credentials are missing");
  }

  // Set expiration time to 24 hours from now (in Unix timestamp seconds)
  const expirationTime = Math.floor(Date.now() / 1000) + 86400;

  // Bunny strictly requires this exact string concatenation order:
  // library_id + api_key + expiration_time + video_id
  const signatureString = `${libraryId}${apiKey}${expirationTime}${videoId}`;
  
  // Hash it using SHA256
  const signature = crypto
    .createHash('sha256')
    .update(signatureString)
    .digest('hex');

  return {
    libraryId,
    videoId,
    expirationTime,
    signature
  };
};

export const generateSecureStreamUrl = (videoId: string): string => {
  const securityKey = process.env.BUNNY_STREAM_TOKEN_KEY;
  const pullZone = process.env.BUNNY_STREAM_PULL_ZONE; 
  const cdnHostname = process.env.CDN_HOSTNAME;

  if (!securityKey || !pullZone) {
    throw new Error("Critical: Missing Bunny Stream token configuration.");
  }

  const streamHostname = cdnHostname || `${pullZone}.b-cdn.net`;

  // Set expiration (e.g., 2 hours from now)
  const expires = Math.floor(Date.now() / 1000) + 7200;

  // CRITICAL: We must sign the DIRECTORY path, not the playlist.m3u8 file path.
  const tokenPath = `/${videoId}/`;

  // Construct the base string exactly as Bunny Token Auth V2 requires
  // Formula: securityKey + tokenPath + expires
  const hashableBase = `${securityKey}${tokenPath}${expires}`;

  // Generate the SHA-256 hash
  let token = crypto
    .createHash('sha256')
    .update(hashableBase)
    .digest('base64');

  // Format the Base64 string to be URL-safe (Bunny strictly requires this)
  token = token
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '');

  // URL-encode the token_path parameter for the query string
  const encodedTokenPath = encodeURIComponent(tokenPath);

  // Use Bunny's path-based token format so the playlist and all nested HLS segment
  // requests inherit the same authorization automatically.
  const secureUrl = `https://${streamHostname}/bcdn_token=${token}&expires=${expires}&token_path=${encodedTokenPath}/${videoId}/playlist.m3u8`;

  return secureUrl;
};

/**
 * Deletes a video permanently from Bunny.net Stream storage.
 * @param videoId The GUID of the video in Bunny.
 * @returns boolean indicating success.
 */
export const deleteBunnyVideo = async (videoId: string): Promise<boolean> => {
  const libraryId = process.env.BUNNY_LIBRARY_ID;
  const apiKey = process.env.BUNNY_API_KEY;

  if (!libraryId || !apiKey) {
    throw new Error("Critical: Bunny API credentials missing.");
  }

  const url = `https://video.bunnycdn.com/library/${libraryId}/videos/${videoId}`;

  const options = {
    method: 'DELETE',
    headers: {
      'Accept': 'application/json',
      'AccessKey': apiKey,
    }
  };

  try {
    const response = await fetch(url, options);

    if (response.ok) {
      return true;
    }

    // If Bunny says it's already gone (404), we consider it a success for our cleanup purposes
    if (response.status === 404) {
      console.warn(`[Drive Service] Video ${videoId} not found in Bunny. Proceeding with local cleanup.`);
      return true;
    }

    const errorData = await response.text();
    throw new Error(`Bunny API Error (${response.status}): ${errorData}`);

  } catch (error) {
    console.error("[Drive Service] Failed to delete video from Bunny:", error);
    throw error;
  }
};