import express from "express";
import { catchAsync } from "../../utils/catchAsync";
import { forgetPassword, resetPassword, selectcategoryandgrade, studentLogin, studentSignup, validatePasswordResetCode, verifyStudentEmail } from "../../controllers/user/studentauth";
const router = express.Router();
router.post("/signup", catchAsync(studentSignup));
router.post("/login", catchAsync(studentLogin));
router.post("/forgot-password", catchAsync(forgetPassword));
router.post("/validate-reset-code", catchAsync(validatePasswordResetCode));
router.post("/reset-password", catchAsync(resetPassword));
router.get("/verify-email", catchAsync(verifyStudentEmail));
router.get("/select", catchAsync(selectcategoryandgrade));
export default router;
